source 'https://rubygems.org'

gem 'dotenv'
gem 'faraday'
gem 'rake'
gem 'semantic_logger'
gem 'telegram-bot-ruby'

# Component requirements
gem 'activemodel', require: 'active_model'
gem 'pg', '~> 0.18'
gem 'sequel'

group :development, :test do
  gem 'cucumber'
  gem 'debug'
  gem 'racc'
  gem 'rspec'
  gem 'rspec_junit_formatter'
  gem 'rubocop', '1.50.2', require: false
  gem 'rubocop-rspec', '2.22.0', require: false
  gem 'simplecov'
  gem 'vcr'
  gem 'webmock'
end

group :development do
  gem 'guard'
  gem 'guard-rspec'
end
